extends Node2D

onready var minutes = 0
onready var waiter = 0
onready var waiterdisabled = false
onready var waiterbagel = false
var bagelGrab = 0
onready var hand = $TextureRect/AlexBackground/Sprite

func _ready():
	UniversalFunctions.update()
	UniversalFunctions.play_dialogue("null", "You are Alex Thorley.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.play_dialogue("null", "You have been waiting for 30 minutes.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "The waitress keeps coming by to ask if you’re ready to order.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You are not. ", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Your date isn't here yet. ", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You wonder if they forgot about you. ", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You are a bit plain, after all.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Not like they’d know that.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "They have never seen you before.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Maybe they could sense it.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "This is a very fancy restaurant.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Definitely not a terrible place to get stood up.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Probably not the worst place you’ve ever been stood up either.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	if waiter >= 1:
		UniversalFunctions.play_dialogue("null", "You can always order some of that cheesecake the waiter has.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "It looks very good.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "Pristine.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "The cherry looks immaculate. ", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "The surface is glossy.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "Actually, that’s probably not a good sign.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "You hope it won’t have any of that weird clear gelatine on top of it that exists solely to make deserts look more appetizing.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "That stuff adds a weird texture.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	if waiter >= 3:
		UniversalFunctions.play_dialogue("null", str("That guy has definitely walked by with that same cheesecake at least " + str(waiter) + " times now."), 0.05)
		yield($CanvasLayer/Dialogue, "close")
		UniversalFunctions.play_dialogue("null", "Is he walking in a... circle?", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		$Timer.starting()
		yield($Timer, "timeout")
		UniversalFunctions.play_dialogue("null", "Oh. You can’t turn around.", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		$Timer.starting()
		yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "You should... have ordered wine. That would have made this less awkward.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "Actually, FUCK that.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Pull yourself together, Thorley!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You want to make a good first impression on your date!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "They probably just got lost!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "They’ll be here any minute!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "That would make perfect sense!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You’ve been late to dates before!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Hundreds of times!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Wait, no.", 0.06)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Not that many times.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "That definitely doesn’t sound right.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	waiterbagel = true
	UniversalFunctions.play_dialogue("null", "Either way, this was not an easy place to find!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "Well, actually it was.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You think?", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Uh.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You do not remember how you got here.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You do not remember waiting.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	if minutes >= 1:
		UniversalFunctions.play_dialogue("null", str("You have been waiting for " +str(30+minutes)+" minutes."), 0.05)
		yield($CanvasLayer/Dialogue, "close")
		$Timer.starting()
		yield($Timer, "timeout")
	UniversalFunctions.play_dialogue_auto("null", "Maybe you should leave soo", 0.05)
	yield($CanvasLayer/Dialogue, "autoclose")
	hand.visible = false
	$AnimationPlayer.play("HandOutStandUp")
	UniversalFunctions.play_dialogue_auto("Alex Thorley", "\"Hey! Sorry I'm lat", 0.05)
	yield($CanvasLayer/Dialogue, "autoclose")
	$AnimationPlayer.play("AwkwardStareStanding")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Oh... my god?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStareStanding")
	UniversalFunctions.play_dialogue("null", "\"God DAMMIT\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	hand.visible = true
	$TextureRect/AlexBackground.position = Vector2(0,0)
	$AnimationPlayer.play("BlankStareSit")
	UniversalFunctions.play_dialogue("null", "You sit down and stare at yourself.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You did not expect your night to go this way.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"...\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You think about how you got into this situation.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "\"...\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	waiterbagel = true
	UniversalFunctions.play_dialogue("null", "Your stomach gurgles.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$TextureRect/TableDressing.visible = false
	$AnimationPlayer.play("MenuBlank")
	UniversalFunctions.play_dialogue("null", "You pick up the menu and look through it.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("MenuAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"So, uh. Have you looked over the menu yet?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("MenuNervous")
	UniversalFunctions.play_dialogue("null", "\"I was thinking of ordering the Filet Mignon.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$TextureRect/TableDressing.visible = true
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Cool. I’ll take that too. I would know what I want.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "It’s true. You would know what you want.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play_backwards("BlankStare")
	UniversalFunctions.play_dialogue("null", "Sometimes.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$TextureRect/TableDressing.visible = false
	$AnimationPlayer.play("MenuWaitressLook")
	UniversalFunctions.play_dialogue("null", "Your waitress returns. She doesn't care that there are now two of you at the table.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Actually, you can’t see her. Or hear her. But you know what she does.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("MenuWaitress")
	UniversalFunctions.play_dialogue("null", "You order and the waitress walks away.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "You look up at yourself once she’s gone.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutEh")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Also just to get this out of the way, I’m not really my type so... I mean.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "\"Yeah, me neither.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Cool.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "\"Split the bill 50/50?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Yup.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "You stare at yourself again.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "Oh god. This is really weird.", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	waiterbagel = true
	UniversalFunctions.play_dialogue("null", "It’s so quiet. You’re on a date with yourself.", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "This is worse than when you thought you stood yourself up.", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Fuck!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "FUCK!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "Fuck.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "You know what... now that you’re looking at yourself right in front of you, maybe you’re not too plain.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Maybe that’s a good thing. Maybe it highlights your features.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Maybe it means you’re easier to look at.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("CuriousStare")
	UniversalFunctions.play_dialogue("null", "You’re too self-conscious. The mirror makes you too hard on yourself.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Maybe your insecurities are unreasonable.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Maybe people just look at you like a person...", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HalfSmileStare")
	UniversalFunctions.play_dialogue("null", "Maybe people even go so far as to say you look... pretty... good.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Yeah.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("SmileStare")
	UniversalFunctions.play_dialogue("null", "You look good.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	if bagelGrab == 3:
		bagelGrab()
	else:
		filetMignon()
	
func bagelGrab():
	hand.visible = false
	$AnimationPlayer.play("MenuWaitressLook")
	UniversalFunctions.play_dialogue("null", "The waitress returns and hands you your Filet Mignons.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	hand.visible = true
	$TextureRect/TableDressing.texture = load("res://Sprites/bagelmeal.png")
	$TextureRect/TableDressing.visible = true
	$AnimationPlayer.play("LookingAtFood")
	UniversalFunctions.play_dialogue("null", "It looks...", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	hand.visible = false
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "...", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankTalkStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "This is a just bagel.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "...", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	$AnimationPlayer.play_backwards("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.lastEnding = 3
	UniversalFunctions.speedrundisable = true
	get_tree().change_scene("res://Credits.tscn")
	
	
func filetMignon():
	hand.visible = false
	$AnimationPlayer.play("MenuWaitressLook")
	UniversalFunctions.play_dialogue("null", "The waitress returns and hands you your Filet Mignons.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	hand.visible = true
	$TextureRect/TableDressing.texture = load("res://Sprites/steak.png")
	$TextureRect/TableDressing.visible = true
	$AnimationPlayer.play("LookingAtFood")
	UniversalFunctions.play_dialogue("null", "It looks delicious.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You can’t look down to see yours but you can see yours.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "The other you’s.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Kind of. It’s slightly obscured by the candle. But you still know yours looks delicious.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "The you that is you, of course.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("CuttingFood")
	UniversalFunctions.play_dialogue("null", "You cut off a piece of your steak.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "A perfect medium-rare.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You still cannot look down to see it, of course.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You are surprisingly good at cutting a steak you can’t see.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("ChewingFood")
	UniversalFunctions.play_dialogue("null", "You watch yourself put the first piece in your mouth and chew at exactly the same time as you.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	if minutes > 0 or UniversalFunctions.speedrundisable == true:
		food()
	else:
		stop()
			
			
			
func food():
	$AnimationPlayer.play("ThisSucks")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"This Filet Mignon sucks.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	hand.visible = false
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "\"I was about to say the same thing.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "\"I’m going to keep eating it, though.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Same.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	hand.visible = true
	$AnimationPlayer.play("ChewingFood")
	UniversalFunctions.play_dialogue("null", "The texture is buttery but it was woefully underseasoned to the point that it’s essentially flavorless garbage.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Fancy restaurants like to leave meat unseasoned and call it classy.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You can’t taste anything but that gross metallic flavor of the meat itself, which isn’t particularly pleasant.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Actually, you can't taste anything.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	hand.visible = false
	$AnimationPlayer.play("SmileStare")
	UniversalFunctions.play_dialogue("null", "\"Well, at least it’s not a bagel.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutSereneSmile")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Hah! Yeah. I would be the one person to understand me.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("SmileStare")
	UniversalFunctions.play_dialogue("null", "\"Hey wait a second... You... understand...\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("Shocked")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"...Oh my god... You’re right.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "\"You’re me! Oh my god, you're me!\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("SuperHappy")
	UniversalFunctions.play_dialogue("Alex Thorley", "[shake rate=15 level=15]\"OH MY GOD!\"[/shake]", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "[shake rate=15 level=15]\"THIS IS THE HAPPIEST DAY OF MY LIFE!\"[/shake]", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("SuperHappyVibrate")
	UniversalFunctions.play_dialogue("null", "You’re practically vibrating you’re so overjoyed.", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You have someone who understands what you’re going through!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Who understands your life!", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "And you’ve finally made yourself appreciate the beauty of your face...", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You have made yourself understand your plainness is not unloveable.", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "...", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.options("Kiss yourself", "Do not")
	yield ($CanvasLayer/Options,"pressed")
	if $CanvasLayer/Options.selected == "Kiss yourself":
		kiss()
	elif $CanvasLayer/Options.selected == "Do not":
		do_not()
	
func do_not():
	$AnimationPlayer.play("HandOutHappy")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Oh my god think of all the stuff we can do now! We can cover for ourselves at work... We’ll have a roommate who’ll never argue with us...\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "\"Ah... speaking of which... We’re probably gonna have to report this. There’s no way this is normal.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"I mean, if this whole thing doesn’t sort itself out with one of us ceasing to exist again before we report it.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "\"...\"", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"...\"", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "\"Aww, shit.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Okay now... now hold on a second. We don’t know that for SURE, right? Like there’s no guarantee one of us is gonna stop existing.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "\"Yeah, but I mean... given the track record...\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"...\"", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "\"...\"", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"It’s not like talking about it can really accomplish anything.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HalfSmileStare")
	UniversalFunctions.play_dialogue("null", "The two yous quickly manage to forget all about your fears as you become engrossed in conversation.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutHappy")
	UniversalFunctions.play_dialogue("null", "You complain to yourself about your workplace environment and the overall absurdity of your life.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("SmileStare")
	UniversalFunctions.play_dialogue("null", "You do not care that you are in public or that civilians might hear you.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutSereneSmile")
	UniversalFunctions.play_dialogue("null", "The only person you’ve seen so far is that one waiter. It's not like it matters.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play_backwards("load")
	yield($AnimationPlayer, "animation_finished")
	$TextureRect/background.play("bedroom")
	$AudioStreamPlayer.stream = load("res://res://Resources/559853__migfus20__mysterious-piano-music-loop.mp3")
	$AudioStreamPlayer.playing = true
	$TextureRect/ChairTruck.visible = false
	$TextureRect/Table.visible = false
	$TextureRect/Waiter2.visible = false
	$TextureRect/Candle.visible = false
	$TextureRect/AlexBackground.visible = false
	$TextureRect/TableDressing.visible = false
	UniversalFunctions.play_dialogue("null", "Eventually, you leave and head back to your residence at the Foundation site you've been stationed at.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You talk the whole way there too.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("load")
	yield($AnimationPlayer, "animation_finished")
	$AnimationPlayer.play("HandOutSereneSmile")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Hah! Think they’ll pay both of us to do nothing if we both stick around?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("SmileStare")
	UniversalFunctions.play_dialogue("null", "You made a joke about something before you got here.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "Something about... how... little you do for... work?", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("CuriousStare")
	UniversalFunctions.play_dialogue("null", "You notice you don’t know what’s going on.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutEh")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"What’s up with you all of a sudden?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("CuriousStare")
	UniversalFunctions.play_dialogue("null", "\"What did I just say, again?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"You made... a joke about how little we do for work?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "\"No I mean, what did I say, specifically.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	yield($AnimationPlayer,"animation_finished")
	$AnimationPlayer.play("AwkwardStare")
	yield($AnimationPlayer,"animation_finished")
	UniversalFunctions.play_dialogue_auto("Alex Thorley", "\"Something about not working very", 0.05)
	yield($CanvasLayer/Dialogue, "autoclose")
	$AnimationPlayer.play("Shocked")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Oh.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	$Timer.starting()
	yield($Timer, "timeout")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Do you remember... What we were talking about before we got here?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "\"No. Do you remember why you were late for our date?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"No.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "\"...\"", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"...\"", 0.02)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("CuriousStare")
	UniversalFunctions.play_dialogue("null", "\"Also I can’t move.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankTalkStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"What?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "\"Yeah, I can’t move.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"But you walked here?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	UniversalFunctions.play_dialogue("null", "\"Right. I know that.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "You consider the possibility of both of you ceasing to exist. Or that neither of you exists right now.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	$AnimationPlayer.play("CuriousStare")
	UniversalFunctions.play_dialogue("null", "\"What do you remember doing before our date?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	
	if UniversalFunctions.lastEnding == null:
		$AnimationPlayer.play("BlankTalkStare")
		UniversalFunctions.play_dialogue("Alex Thorley", "\"I don't remember anything before our date.\"", 0.05)
		yield($CanvasLayer/Dialogue, "close")
	elif UniversalFunctions.lastEnding == 0:
		$AnimationPlayer.play("AwkwardStare")
		UniversalFunctions.play_dialogue("Alex Thorley", "\"Everything was so... dizzy.\"", 0.05)
		yield($CanvasLayer/Dialogue, "close")
	elif UniversalFunctions.lastEnding == 1:
		$AnimationPlayer.play("HandOutHappy")
		UniversalFunctions.play_dialogue("Alex Thorley", "\"I was on my way home with a new friend.\"", 0.05)
		yield($CanvasLayer/Dialogue, "close")
	elif UniversalFunctions.lastEnding == 2:
		$AnimationPlayer.play("BlankTalkStare")
		UniversalFunctions.play_dialogue("Alex Thorley", "\"I was sitting... Right here. Talking to someone.\"", 0.05)
		yield($CanvasLayer/Dialogue, "close")
	elif UniversalFunctions.lastEnding == 2:
		$AnimationPlayer.play("BlankTalkStare")
		UniversalFunctions.play_dialogue("Alex Thorley", "\"I remember a bagel\"", 0.05)
		yield($CanvasLayer/Dialogue, "close")
		
	
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"What about you?\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "You remember lots about yourself. You remember the orientation. You remember the burger. You remember being accused of murder.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HalfSmileStare")
	UniversalFunctions.play_dialogue("null", "\"I remember the bagel.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"I do too.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "You remember reading. You remember writing. You remember looking at a website on a screen.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "You are not Alex Thorley.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "You knew this, of course.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	$AnimationPlayer.play("HandOutSereneSmile")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Well, it was nice to meet you.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankTalkStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"I’ll see you around.\"", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	$Timer.starting()
	$AnimationPlayer.play_backwards("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.lastEnding = 2
	get_tree().change_scene("res://Credits.tscn")
	
	
func kiss():
	$AnimationPlayer.play_backwards("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.play_dialogue("null", "You lean towards yourself...", 0.06)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Reach up and grasp your smiling face...", 0.06)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Then close your eyes.", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You feel your lips on yours for just a moment...", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "Then you pull back and stare at yourself one last time.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("BlankStare")
	yield($AnimationPlayer, "animation_finished")
	$AnimationPlayer.play("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"...\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "\"...\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Okay actually, that was really weird.\"", 0.06)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("NervousStare")
	UniversalFunctions.play_dialogue("null", "\"Yeah... let's...never... do that... again.\"", 0.06)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Agreed.\"", 0.06)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("SmileStare")
	UniversalFunctions.play_dialogue("null", "\"But still! If we forget about this I can see this becoming the start of a beautiful friendship!\"", 0.04)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutSereneSmile")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Yes! I finally have someone to talk to! Someone who understands!\"", 0.04)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutStandUpEnd")
	UniversalFunctions.play_dialogue("null", "You stand up and hold a hand out to yourself.", 0.05)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "\"Come on! Let’s go someplace quiet where we can talk about all the things we can't tell anyone else!\"", 0.04)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play_backwards("load")
	yield($AnimationPlayer, "animation_finished")
	$TextureRect/background.play("crossing")
	$AudioStreamPlayer.stream = load("res://Resources/559850__migfus20__jazz-background-music-loop.mp3")
	$AudioStreamPlayer.playing = true
	$TextureRect/ChairTruck.visible = false
	$TextureRect/Table.visible = false
	$TextureRect/Waiter2.visible = false
	$TextureRect/Candle.visible = false
	$TextureRect/AlexBackground.visible = false
	$TextureRect/TableDressing.visible = false
	$AnimationPlayer.play("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.play_dialogue("null", "You walk outside with yourself, talking all the way. You don't know what about. You can't hear it.", 0.04)
	yield($CanvasLayer/Dialogue, "close")
	UniversalFunctions.play_dialogue("null", "You turn back towards yourself and smile as you walk through the intersection. Nothing could shake your good mood.", 0.04)
	yield($CanvasLayer/Dialogue, "close")
	$TextureRect/AlexBackground.visible = true
	$AnimationPlayer.play("StandingNight")
	yield($AnimationPlayer, "animation_finished")
	$AnimationPlayer.play("StandingNightTalk")
	UniversalFunctions.play_dialogue_auto("null", "\"Want to get some icecream before we\"", 0.04)
	yield($CanvasLayer/Dialogue, "autoclose")
	$AnimationPlayer.play("Truck")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.play_dialogue("null", "A truck comes out of nowhere and hits you. You die instantly.", 0.04)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	UniversalFunctions.play_dialogue("null", "Well, shit.", 0.04)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play_backwards("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.lastEnding = 1
	get_tree().change_scene("res://Credits.tscn")


func stop():
	$AudioStreamPlayer.stop()
	waiterdisabled = true
	hand.visible = false
	$AnimationPlayer.play("STOP")
	UniversalFunctions.play_dialogue_auto_set("Alex Thorley", "[shake rate=15 level=15]\"STOP!\"[/shake]", 0.02, 3)
	yield($CanvasLayer/Dialogue, "autoclose")
	$AnimationPlayer.play("ThisSucks")
	UniversalFunctions.play_dialogue_auto_set("Alex Thorley", "\"God\"", 0.02, 1.5)
	yield($CanvasLayer/Dialogue, "autoclose")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue_auto("Alex Thorley", "\"Is it over?\"", 0.07)
	yield($CanvasLayer/Dialogue, "autoclose")
	$AnimationPlayer.play("NervousStare")
	$Timer.starting()
	yield($Timer, "timeout")
	$AnimationPlayer.play("HandOutAwkward")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Look... I seem like a great person and all...\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStare")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"But... we're moving way too fast with this.\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutEh")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"I'm just not ready to jump into a relationship this quickly.\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("ThisSucks")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Also, that was making me super dizzy.\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutHappy")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Keep in touch?\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("HandOutEh")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"I mean... we're both probably going to the same place anyways.\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play("AwkwardStareStanding")
	UniversalFunctions.play_dialogue("Alex Thorley", "\"Goodbye.\"", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$AnimationPlayer.play_backwards("HandOutStandUp")
	UniversalFunctions.play_dialogue("null", "Looks like you're not that into speedrunners.", 0.07)
	yield($CanvasLayer/Dialogue, "close")
	$Timer.starting()
	yield($Timer, "timeout")
	$AnimationPlayer.play_backwards("load")
	yield($AnimationPlayer, "animation_finished")
	UniversalFunctions.lastEnding = 0
	UniversalFunctions.speedrundisable = true
	get_tree().change_scene("res://Credits.tscn")


func _on_Minutes_timeout():
	minutes += 1



func _on_Waiter_timeout():
	waiter += 1
	if waiterdisabled == false and waiterbagel == false:
		$TextureRect/Waiter2/WaiterAnims.play("move")
		$Waiter.stop()
		yield($TextureRect/Waiter2/WaiterAnims, "animation_finished")
		$Waiter.start()
	elif waiterdisabled == false and waiterbagel == true:
		$TextureRect/BagelWaiter/Bagel3.visible = true
		$TextureRect/BagelWaiter/WaiterAnims.play("move")
		$Waiter.stop()
		yield($TextureRect/Waiter2/WaiterAnims, "animation_finished")
		$Waiter.start()
		waiterbagel = false



func _on_Bagel3_pressed():
	$TextureRect/BagelWaiter/Bagel3.visible = false
	bagelGrab += 1
	print(bagelGrab)
	waiterbagel = false
	$Waiter.start()
